INSERT INTO tb_user (name, email, password) VALUES ('Bob', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Ana', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_genre (name) VALUES ('Ação');
INSERT INTO tb_genre (name) VALUES ('Animação');
INSERT INTO tb_genre (name) VALUES ('Aventura');
INSERT INTO tb_genre (name) VALUES ('Drama');
INSERT INTO tb_genre (name) VALUES ('Ficção científica');
INSERT INTO tb_genre (name) VALUES ('Terror');

INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Mulher-Maravilha 1984', 'Uma nova era de maravilhas começa.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/srYya1ZlI97Au4jUYAktDe3avyA.jpg', 'Em 1984, Diana Prince entra em conflito com dois inimigos formidáveis, Maxwell Lord e a Mulher-Leopardo, enquanto reencontra misteriosamente com seu antigo interesse amoroso Steve Trevor.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Godzilla vs. Kong', 'Um dos dois cairá.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg', 'Em uma época em que os monstros andam na Terra, a luta da humanidade por seu futuro coloca Godzilla e Kong em rota de colisão que verá as duas forças mais poderosas da natureza no planeta se confrontarem em uma batalha espetacular para as idades.', 5);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Projeto Gemini', 'Quem pode salvá-lo de você mesmo.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/c3F4P2oauA7IQmy4hM0OmRt2W7d.jpg', 'Henry Brogan é um assassino de elite que se torna o alvo de um agente misterioso que aparentemente pode prever todos os seus movimentos. Ele logo descobre que o homem que está tentando matá-lo é uma versão mais jovem, rápida e clonada de si mesmo.', 5);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Coringa', 'Coloque um sorriso nessa cara.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg', 'Arthur Fleck trabalha como palhaço para uma agência de talentos e, toda semana, precisa comparecer a uma agente social, devido aos seus conhecidos problemas mentais. Após ser demitido, Fleck reage mal à gozação de três homens em pleno metrô e os mata.', 4);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Vingadores: Ultimato', 'O fim de uma era!', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg', 'Após os eventos devastadores de "Vingadores: Guerra Infinita", o universo está em ruínas devido aos esforços do Titã Louco, Thanos. Com a ajuda de aliados remanescentes, os Vingadores devem se reunir mais uma vez a fim de desfazer as ações de Thanos.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('It - A Coisa', 'Você Também vai Flutuar.', 2017, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/9IHPpCSAmP4KO3gCq7GpgFjVKcy.jpg', 'Um grupo de sete adolescentes de Derry, uma cidade no Maine, formam o auto-intitulado "Losers Club", o clube dos perdedores.', 6);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('It: Capítulo Dois', 'Você Vai Flutuar de Novo', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/8moTOzunF7p40oR5XhlDvJckOSW.jpg', 'Vinte e sete anos depois dos eventos que chocaram os adolescentes que faziam parte do Clube dos Perdedores, os amigos realizam uma reunião.', 6);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('O Iluminado', 'Ele veio como zelador, mas este hotel tinha seus próprios guardiões, que estavam lá há muito tempo.', 1980, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/mmd1HnuvAzFc4iuVJcnBrhDNEKr.jpg', 'Durante o inverno, um homem é contratado para ficar como vigia em um hotel no Colorado e vai para lá com a mulher e seu filho.', 6);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Doutor Sono', 'Atreva-se a voltar.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/ap6Zc5NDOfbZaMhkRDyghbGeLf0.jpg', 'Na infância, Danny Torrance conseguiu sobreviver a uma tentativa de homicídio por parte do pai, um escritor perturbado por espíritos malignos. Danny cresceu, agora ele é um adulto traumatizado e alcoólatra.', 6);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Jogador N° 1', 'Uma aventura muito além do mundo real.', 2018, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/5a7lMDn3nAj2ByO0X1fg6BhUphR.jpg', 'Num futuro distópico, situado em 2044, Wade Watts, como o resto da humanidade, prefere a realidade virtual do jogo OASIS ao mundo real.', 5);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('John Wick 3: Parabellum', 'Toda ação tem uma consequência.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/vVpEOvdxVBP2aV166j5Xlvb5Cdc.jpg', 'Após assassinar o chefe da máfia Santino D''Antonio no Hotel Continental, John Wick passa a ser perseguido pelos membros da Alta Cúpula sob a recompensa de U$14 milhões.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Espiral - O Legado de Jogos Mortais', 'Descubra um novo capítulo.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/4JoR5107gSdOK1ICzvWikpIp2Vz.jpg', 'Sob o comando do veterano da polícia Marcus, o detetive Ezekiel "Zeke" Banks se une ao seu parceiro novato Willem para desvendar uma série de assassinatos terríveis que estão acontecendo na cidade.', 6);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Mortal Kombat', 'Get over here.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg', 'Nova aventura baseada no videogame Mortal Kombat. Na história, um jovem que nunca treinou artes marciais acaba envolvido em um gigantesco torneio de luta envolvendo guerreiros da Terra e lutadores e outras dimensões.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Operação Big Hero', 'Prepare-se para ação.', 2014, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/4s2d3xdyqotiVNHTlTlJjrr3q0H.jpg', 'O grande robô inflável está sempre a postos para cuidar de Hiro Hamada. Quando algo devastador assola a cidade, o menino prodígio, seus amigos e o robô formam um grupo de heróis para combater o mal.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Doutor Estranho', 'As impossibilidades são infinitas.', 2016, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/eQN31P4IEhyp6NkdccvppJnyuJ4.jpg', 'Da Marvel Studios vem “Doctor Strange”, a história do mundialmente famoso neurocirurgião Dr. Stephen Strange, cuja vida muda para sempre depois de um terrível acidente de carro, que o rouba do uso de suas mãos.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Homem-Aranha: De Volta ao Lar', 'O dever de casa pode esperar. A cidade não.', 2017, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/vMNEvp4wKAkDIODZjz5BsqVWY9y.jpg', 'Depois de atuar ao lado dos Vingadores, chegou a hora do pequeno Peter Parker (Tom Holland) voltar para casa e para a sua vida, já não mais tão normal.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Homem-Aranha: Longe de Casa', 'Continuar é preciso.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/tq6yTPDmM8f5IMEiCyy9GgzX07G.jpg', 'Peter Parker está em uma viagem de duas semanas pela Europa, ao lado de seus amigos de colégio, quando é surpreendido pela visita de Nick Fury.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Parasita', 'Aja como se fosse o dono do lugar.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cI1RBfqXbWaITTjcKGYLhd9F083.jpg', 'Toda a família de Ki-taek está desempregada, vivendo num porão sujo e apertado. Uma obra do acaso faz com que o filho adolescente da família comece a dar aulas de inglês à garota de uma família rica.', 4);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Monster Hunter', 'Junte-se à caçada.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/z8TvnEVRenMSTemxYZwLGqFofgF.jpg', 'Baseado no jogo da Capcom chamado Monster Hunter, a tenente Artemis e seus soldados são transportados para um novo mundo.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Invocação do Mal', 'Baseado em arquivos de uma investigação real do casal Warren.', 2013, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/mXndmCbpvlqnD6po0EMfxEZcUSn.jpg', 'Harrisville, Rhode Island, Estados Unidos, 1968.', 6);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Invocação do Mal 2', 'A próxima história real baseada nos casos de Ed e Lorraine Warren.', 2016, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/4mfFtlGeInPrQVm1hpv7th02yjx.jpg', 'Sete anos após os eventos de Invocação do Mal (2013), Lorraine (Vera Farmiga) e Ed Warren (Patrick Wilson) desembarcam na Inglaterra para ajudar uma família atormentada por uma manifestação poltergeist na filha.', 6);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Frozen II', 'Descubra o passado. Enfrente o futuro.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg', 'De volta à infância de Elsa e Anna, as duas garotas descobrem uma história do pai, quando ainda era príncipe de Arendelle.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Os Mercenários 3', 'Nova equipe. Nova atitude. Nova missão.', 2014, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/sJDBJxKWG7h3VpG6jc9Mm9bw4kG.jpg', 'Barney e sua trupe de mercenários resgatam Doc, um dos integrantes do grupo, que estava preso há oito anos.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Velozes e Furiosos: Desafio em Tóquio', 'Adrenalina a cada curva!', 2006, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/eJciNVeMWekmBAeT7HrDP4DWmFb.jpg', 'Sean Boswell é um piloto de rua que desafia seu rival e bate o carro no fim da corrida.', 1);

INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Filme mais ou menos', 1, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Interessante, recomendo!', 1, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Que filme massa!!!', 2, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Gostei muito do filme. Foi muito bom mesmo. Pena que durou pouco', 6, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Gostei muito do filme. Foi muito bom mesmo. Pena que durou pouco', 6, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Gostei muito do filme. Foi muito bom mesmo. Pena que durou pouco', 6, 2);
-- INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Gostei muito do filme. Foi muito bom mesmo. Pena que durou pouco', 6, 2);